runner:
  name: github-action-labs
  namespace: arc-runners
  repository: psarangi550/github-action-labs
  replicas: 1
  labels:
    - github-action-labs
  image:
    repository: ghcr.io/psarangi550/github-action-labs-runner
    tag: v1.0.1
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-pull